"""agrega estatus a materia_prima_unitaria

Revision ID: 5b21b4d94815
Revises: 7e548f01a28e
Create Date: 2026-04-05 22:33:10.599292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b21b4d94815'
down_revision = '7e548f01a28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima_unitaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima_unitaria', schema=None) as batch_op:
        batch_op.drop_column('estatus')

    # ### end Alembic commands ###
