"""empty message

Revision ID: 69b91be4a300
Revises: 83934dbcd083
Create Date: 2026-04-01 19:56:49.492849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69b91be4a300'
down_revision = '83934dbcd083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('folio'))

    op.drop_table('ordenes_compra')
    op.drop_table('detalles_compra')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('rfc'))

    op.drop_table('proveedores')
    op.drop_table('materias_primas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias_primas',
    sa.Column('id_materia', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('categoria', mysql.ENUM('Canal', 'Insumo', 'Reventa'), nullable=False),
    sa.Column('unidad_compra', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('unidad_estandar', mysql.ENUM('g', 'ml', 'pza'), nullable=False),
    sa.Column('factor_conversion', mysql.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('tipo_merma', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pct_merma', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('stock_minimo', mysql.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('stock_actual', mysql.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('costo_promedio', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', mysql.DATETIME(), nullable=True),
    sa.Column('proveedor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('materias_primas_ibfk_1')),
    sa.PrimaryKeyConstraint('id_materia'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('proveedores',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('rfc', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('estatus', mysql.ENUM('activo', 'inactivo'), nullable=False),
    sa.Column('contacto', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('productos', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('condicion_pago', mysql.ENUM('contado', 'credito_8', 'credito_15', 'credito_30'), nullable=False),
    sa.Column('dias_entrega', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('notas', mysql.TEXT(), nullable=True),
    sa.Column('fecha_registro', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('rfc'), ['rfc'], unique=True)

    op.create_table('detalles_compra',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orden_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('materia_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('unidad_compra', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('factor_conversion', mysql.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('unidad_estandar', mysql.ENUM('g', 'ml', 'pza'), nullable=False),
    sa.Column('costo_unitario', mysql.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias_primas.id_materia'], name=op.f('detalles_compra_ibfk_2')),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], name=op.f('detalles_compra_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ordenes_compra',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('folio', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('proveedor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), nullable=False),
    sa.Column('fecha_entrega', sa.DATE(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), nullable=True),
    sa.Column('estado', mysql.ENUM('pendiente', 'recibida', 'cancelada'), nullable=False),
    sa.Column('notas', mysql.TEXT(), nullable=True),
    sa.Column('total', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('fecha_registro', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('ordenes_compra_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ordenes_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('folio'), ['folio'], unique=True)

    # ### end Alembic commands ###
