"""Agregar usuario a lote

Revision ID: 6f2a1c524698
Revises: a1b2c3d4e5f6
Create Date: 2026-04-10 23:12:31.498510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f2a1c524698'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detallesTicket',
    sa.Column('idDetalle', sa.Integer(), nullable=False),
    sa.Column('idTicket', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.idProducto'], ),
    sa.ForeignKeyConstraint(['idTicket'], ['ticket.idTicket'], ),
    sa.PrimaryKeyConstraint('idDetalle')
    )
    op.drop_table('detallesticket')
    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idUsuario', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['idUsuario'], ['id'])

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.alter_column('nombreMateriaPrima',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=25),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.alter_column('nombreMateriaPrima',
               existing_type=sa.String(length=25),
               type_=mysql.VARCHAR(length=60),
               nullable=True)

    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idUsuario')

    op.create_table('detallesticket',
    sa.Column('idDetalle', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idTicket', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idProducto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtotal', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.idProducto'], name=op.f('detallesticket_ibfk_2')),
    sa.ForeignKeyConstraint(['idTicket'], ['ticket.idTicket'], name=op.f('detallesticket_ibfk_1')),
    sa.PrimaryKeyConstraint('idDetalle'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('detallesTicket')
    # ### end Alembic commands ###
