"""unique constraints en modelos

Revision ID: 711ec80ea3c6
Revises: 5b21b4d94815
Create Date: 2026-04-06 11:25:55.012812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711ec80ea3c6'
down_revision = '5b21b4d94815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombreCategoria'])

    with op.batch_alter_table('conversor', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombreConversor'])

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombreMateriaPrima'])

    with op.batch_alter_table('materia_proveida', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombreMateriaProveida'])

    with op.batch_alter_table('orden_compra', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['numeroLote'])

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['NombreProducto'])

    with op.batch_alter_table('unidad_medida', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombreUnidadMedida'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidad_medida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('orden_compra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('materia_proveida', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('materia_prima', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('conversor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
