"""refactor orden_compra header y materia_prima_unitaria lineas

Revision ID: 7e548f01a28e
Revises: 69b91be4a300
Create Date: 2026-04-05 22:12:24.015148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e548f01a28e'
down_revision = '69b91be4a300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima_unitaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidadDeUnidad', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('cantidadPorUnidad', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('precioPorUnidad', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('totalMateria', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('totalCosto', sa.Float(), nullable=False))

    with op.batch_alter_table('orden_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idProveedor', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('totalOrden', sa.Float(), nullable=False))
        batch_op.alter_column('numeroLote',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('estatus',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('EnCurso', 'Recibida', 'Cancelada'),
               nullable=False)
        batch_op.create_foreign_key(None, 'proveedor', ['idProveedor'], ['id'])
        batch_op.drop_column('totalMateria')
        batch_op.drop_column('precioPorUnidad')
        batch_op.drop_column('cantidadPorUnidad')
        batch_op.drop_column('totalCosto')
        batch_op.drop_column('cantidadDeUnidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidadDeUnidad', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totalCosto', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cantidadPorUnidad', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('precioPorUnidad', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('totalMateria', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('estatus',
               existing_type=sa.Enum('EnCurso', 'Recibida', 'Cancelada'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('numeroLote',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('totalOrden')
        batch_op.drop_column('idProveedor')

    with op.batch_alter_table('materia_prima_unitaria', schema=None) as batch_op:
        batch_op.drop_column('totalCosto')
        batch_op.drop_column('totalMateria')
        batch_op.drop_column('precioPorUnidad')
        batch_op.drop_column('cantidadPorUnidad')
        batch_op.drop_column('cantidadDeUnidad')

    # ### end Alembic commands ###
