"""modulo compras: ordenes_compra, detalles_compra, proveedor_id en materias_primas

Revision ID: 83934dbcd083
Revises: 43a983f0ebe4
Create Date: 2026-04-01 18:50:23.695765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83934dbcd083'
down_revision = '43a983f0ebe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proveedores', ['proveedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materias_primas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proveedor_id')

    # ### end Alembic commands ###
