"""Agregar usuario a lote

Revision ID: ca8efd558bfa
Revises: 6f2a1c524698
Create Date: 2026-04-12 14:12:54.626264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca8efd558bfa'
down_revision = '6f2a1c524698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detallesTicket',
    sa.Column('idDetalle', sa.Integer(), nullable=False),
    sa.Column('idTicket', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.idProducto'], ),
    sa.ForeignKeyConstraint(['idTicket'], ['ticket.idTicket'], ),
    sa.PrimaryKeyConstraint('idDetalle')
    )
    op.drop_table('detallesticket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detallesticket',
    sa.Column('idDetalle', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idTicket', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idProducto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtotal', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['idProducto'], ['producto.idProducto'], name=op.f('detallesticket_ibfk_2')),
    sa.ForeignKeyConstraint(['idTicket'], ['ticket.idTicket'], name=op.f('detallesticket_ibfk_1')),
    sa.PrimaryKeyConstraint('idDetalle'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('detallesTicket')
    # ### end Alembic commands ###
