"""Agregar bloqueo por intentos

Revision ID: cca69fb2914a
Revises: fdd2ac9997d8
Create Date: 2026-03-30 19:47:49.324516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cca69fb2914a'
down_revision = 'fdd2ac9997d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('intentos_fallidos',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('intentos_fallidos',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
