"""Agregar campo para tokens expirados a usuarios

Revision ID: dd52574ad30b
Revises: fb86cfc58dd6
Create Date: 2026-03-31 18:11:17.525898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd52574ad30b'
down_revision = 'fb86cfc58dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_expiration')

    # ### end Alembic commands ###
