"""add fechaCaducidad to materia_prima_unitaria

Revision ID: e1b74322c4e4
Revises: 711ec80ea3c6
Create Date: 2026-04-07 19:58:20.669192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b74322c4e4'
down_revision = '711ec80ea3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima_unitaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaCaducidad', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia_prima_unitaria', schema=None) as batch_op:
        batch_op.drop_column('fechaCaducidad')

    # ### end Alembic commands ###
