"""Agregar campos a user

Revision ID: fb86cfc58dd6
Revises: cca69fb2914a
Create Date: 2026-03-30 20:05:14.744953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb86cfc58dd6'
down_revision = 'cca69fb2914a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_sesion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ultima_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('session_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_token')
        batch_op.drop_column('ultima_ip')
        batch_op.drop_column('ultima_sesion')

    # ### end Alembic commands ###
