"""Agregar campos a user

Revision ID: fdd2ac9997d8
Revises: 
Create Date: 2026-03-30 19:40:53.210071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd2ac9997d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intentos_fallidos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bloqueado_hasta')
        batch_op.drop_column('intentos_fallidos')

    # ### end Alembic commands ###
